### PR TITLE
Added `update_coordinators` to `AdminWebsocket`

### PR DESCRIPTION
**Pull request by guillemcordoba**

### CODE REVIEW

**Review by jost-s — CHANGES_REQUESTED** [review]
Great! I've forgotten that the last times, so this time I'm asking you to add an entry to the changelog =)

**Comment by guillemcordoba** [comment]
Oh right! Done.

**Review by jost-s — APPROVED** [review]
Greaaaat!

**Comment by jost-s** [comment]
@guillemcordoba 

released as v0.5.0-dev.27

**Pull request merged**
