### PR TITLE
Build/holochain 0.3.x

### PR DESCRIPTION
**Pull request by mattyg**
Bump support for latest holochain 0.3.0-beta-dev.22

Supersedes #21

### CODE REVIEW

**Comment by jost-s** [comment]
@mattyg Please resolve conflicts, it's cumbersome to do that for a lock file.

**Comment by mattyg** [comment]
> @mattyg Please resolve conflicts, it's cumbersome to do that for a lock file.

Okay all set @jost-s

**Comment by mattyg** [comment]
okay @jost-s now its *actually* all set

**Review by jost-s — APPROVED** [review]
Great shtuff!

**Pull request merged**
