### PR TITLE
Added on_signal

### PR DESCRIPTION
**Pull request by guillemcordoba**
I also added a test... Let me know if I should do anything else.

### CODE REVIEW

**Comment by jost-s** [comment]
Sorry for taking so long. I'll get to this shortly.

**Comment by jost-s** [comment]
Is this intended for 0.2 (main) or 0.3 (develop)?

**Comment by guillemcordoba** [comment]
Oh! 0.3 I guess... Let me try to change the target branch.

**Comment by guillemcordoba** [comment]
Wait a second, I'm fixing the conflicts...

**Comment by guillemcordoba** [comment]
Closed in favor of https://github.com/holochain/holochain-client-rust/pull/42

**Pull request closed without merging**
