### PR TITLE
build(serde): pin to v1.0.166

### PR DESCRIPTION
**Pull request by jost-s**

### CODE REVIEW

**Comment by ThetaSinner** [comment]
@jost-s I don't think this will pin to 1.0.166 in projects that use the client. Setting it like that is equivalent to setting a minimum version and letting the consumer choose an equal or higher version. The least intrusive way I could think of pinning in Holochain was using `serde = { version = ">= 1.0, <= 1.0.166" }`

https://github.com/holochain/holochain/blob/develop-0.2/crates/holochain/Cargo.toml#L60C1-L60C41

**Comment by jost-s** [comment]
@ThetaSinner Sorry, that was bollix. I omitted the `=` sign. Does serde have to be between 1.0 and 1.0.166?

**Comment by ThetaSinner** [comment]
It definitely has to be `<= 1.0.166` but I think it leaves it more open for projects to be able to use any version of serde from 1.0 onwards

**Comment by ThetaSinner** [comment]
I'm not sure if `<= 1.0.166` implies `>= 1.0` actually, maybe it does

**Comment by jost-s** [comment]
Hard to know, yes. I'll copy the range you specified.

**Pull request merged**
