### PR TITLE
Bump Holochain deps to resolve bad publish

### PR DESCRIPTION
**Pull request by ThetaSinner**
This also ends up needing to include the `allowed_origins` change

### CODE REVIEW

**Comment by ThetaSinner** [comment]
Sorry, not quite ready

**Comment by ThetaSinner** [comment]
Okay, good now

**Comment by ThetaSinner** [comment]
Meh, the lack of a cache for macos is causing problems here

**Comment by jost-s** [comment]
> Meh, the lack of a cache for macos is causing problems here

Yes, it has done that for a while unfortunately.

**Review by jost-s — APPROVED** [review]
Thank you for this

**Pull request merged**
